on:
  schedule:
    - cron: '50 14 * * *'

name: Update algolia indexes for docs

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run algolia crawler
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: '0BOLUCHQ0E'
          algolia_api_key: ${{ secrets.ALGOLIA_API}}
          file: 'algolia.config.json'
