on:
  schedule:
    - cron: '50 14 * * *'
  push:
    branches:
      - 'docs'

name: Update algolia indexes for docs

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: set config-date
        env:
          TODAY=`date +%Y-%m-%d`
          YESTERDAY=`date -v-1d +%Y-%m-%d`
        run: |
          sed -i "s/__TODAY_DATE__/${TODAY}/" algolia.config.json
          sed -i "s/__YESTER_DATE__/${YESTERDAY}/" algolia.config.json
      - name: Run algolia crawler
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_application_id: '0BOLUCHQ0E'
          algolia_api_key: ${{ secrets.ALGOLIA_API}}
          file: 'algolia.config.json'
